import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MSWComponent } from "./_component/MSWComponent";
import { ModalProvider } from "@/components/Modal/context";
import { ModalContainer } from "@/components/Modal/useModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <MSWComponent />
        <ModalProvider>
          {children}
          <ModalContainer />
          <div id="modal-root" />
        </ModalProvider>
      </body>
    </html>
  );
}
